[package]
name = "wgp"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
structopt = {version="0.3.26", default-features = false }

[[bin]]
name = "wgp"
path = "src/main.rs"


[build]
rustflags = ["-C", "target-feature=+crt-static"]
